# Generated by Django 4.0.4 on 2022-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=5000)),
                ('db_name', models.CharField(max_length=5000)),
                ('user_id', models.CharField(max_length=5000)),
                ('parent_id', models.CharField(max_length=5000)),
                ('school_id', models.CharField(max_length=5000)),
            ],
        ),
    ]
