# Generated by Django 3.2.16 on 2023-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parent_api', '0002_auto_20220530_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerparent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='managerparent',
            name='mobile_token',
            field=models.CharField(default='sadf', max_length=5000),
        ),
        migrations.AlterField(
            model_name='managerparent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
